name: Base

on:
  workflow_call: 
    inputs: 
      aseprite-git-ref:
        required: false
        type: string
        description: The desired Aseprite git ref to build from.
        default: main
      aseprite-build-type:
        required: false
        type: string
        description: Usually one of 'Debug', 'Release', or 'RelWithDebInfo'.
        default: Release

    secrets:
      ghcr-token:
        required: true
        description: Access token to the GitHub Container Registry associated with the repository owner.

jobs:
  build-and-push:
    name: Build Aseprite ${{ inputs.aseprite-git-ref }} (${{ inputs.aseprite-build-type }}) and Push to ghcr.io/${{ github.repository_owner }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr-token }}
      - uses: docker/bake-action@v6
        with:
          pull: true
          push: true
          no-cache: true
          source: .
        env:
          ASEPRITE_BUILD_TYPE: ${{ inputs.aseprite-build-type }}
          ASEPRITE_GIT_REF: ${{ inputs.aseprite-git-ref }}
          IMAGES_PREFIX: ghcr.io/${{ github.repository_owner }}/
